create table tb_role (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
create table tb_users (id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
alter table if exists tb_users add constraint UK_grd22228p1miaivbn9yg178pm unique (email);
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FKpn4njnr07hiiam9pg4pp3xan7 foreign key (user_id) references tb_users;
